/**
 * @file     PKILogTableDefine.hpp
 *
 * @desc     PKIMSGD 로그 리스트
 * @author   박지영(jypark@pentasecurity.com)
 * @since    2002.01.02
 *
 */

/**
 * NOTE : Do not modify the content of this file directly. If this file is regenerated by
 *        file-generating script your modification will be overwritten
 */

/**
 * System 관련 이벤트
 */

#include "Log.hpp"

#define LOG_CATEGORY_SYSTEM                                  "SYSTEM"
#define LOG_CAMSGD_START_DAEMON_N                         	 11001
#define LOG_CAMSGD_START_DAEMON_C                            "신규 실행"

#define LOG_CAMSGD_FAIL_TO_LOAD_PRIKEY_N                  	 11002
#define LOG_CAMSGD_FAIL_TO_LOAD_PRIKEY_C                     "신규 실행 실패(비공개키 복호화 실패)"

#define LOG_CAMSGD_FAIL_TO_LOAD_CERT_N                    	 11003
#define LOG_CAMSGD_FAIL_TO_LOAD_CERT_C                       "신규 실행 실패(인증서 가져오기 실패)"

#define LOG_CAMSGD_INVALID_HISTORY_FILE_N                 	 11004
#define LOG_CAMSGD_INVALID_HISTORY_FILE_C                    "신규 실행 실패(잘못된 History 파일)"

#define LOG_CAMSGD_FAIL_TO_GET_DBSETTINGS_START_N         	 11005
#define LOG_CAMSGD_FAIL_TO_GET_DBSETTINGS_START_C            "신규 실행 실패(DB 설정값 가져오기 실패)"

#define LOG_CAMSGD_FAIL_TO_CONNECT_DB_START_N             	 11006
#define LOG_CAMSGD_FAIL_TO_CONNECT_DB_START_C                "신규 실행 실패(DB 연결 실패)"

#define LOG_CAMSGD_INVALID_DB_TABLE_N                     	 11007
#define LOG_CAMSGD_INVALID_DB_TABLE_C                        "신규 실행 실패(잘못된 DB Table)"

#define LOG_CAMSGD_FAIL_TO_GET_CA_INFO_N                  	 11008
#define LOG_CAMSGD_FAIL_TO_GET_CA_INFO_C                     "신규 실행 실패(DB로부터 초기화를 위한 정보를 가져오는데 실패)"

#define LOG_CAMSGD_FAIL_TO_GET_SYMMALG_N                  	 11009
#define LOG_CAMSGD_FAIL_TO_GET_SYMMALG_C                     "기본 대칭키 암호화 알고리즘 값 가져오기 실패"

#define LOG_CAMSGD_STOP_DAEMON_N                          	 11010
#define LOG_CAMSGD_STOP_DAEMON_C                             "수행 중단"

#define LOG_CAMSGD_FAIL_TO_FORK_DAEMON_N                  	 11011
#define LOG_CAMSGD_FAIL_TO_FORK_DAEMON_C                     "fork 실패"

#define LOG_CAMSGD_TERMINATE_BY_ALARM_N                    	 11012
#define LOG_CAMSGD_TERMINATE_BY_ALARM_C                      "시간 초과로 종료"

/**
 * CRL 관련 이벤트
 */
#define LOG_CATEGORY_CRL                                     "CRL"
#define LOG_CAMSGD_CRL_UPDATED_N                          	 12001
#define LOG_CAMSGD_CRL_UPDATED_C                             "CRL 갱신"

#define LOG_CAMSGD_FAIL_TO_GET_DBSETTINGS_CRL_N           	 12002
#define LOG_CAMSGD_FAIL_TO_GET_DBSETTINGS_CRL_C              "CRL 갱신 실패(DB 설정값 가져오기 실패)"

#define LOG_CAMSGD_FAIL_TO_CONNECT_DB_CRL_N               	 12003
#define LOG_CAMSGD_FAIL_TO_CONNECT_DB_CRL_C                  "CRL 갱신 실패(DB 연결 실패)"

#define LOG_CAMSGD_FAIL_TO_FIND_CRL_UPDATEPERIOD_N        	 12004
#define LOG_CAMSGD_FAIL_TO_FIND_CRL_UPDATEPERIOD_C           "CRL 갱신 주기 값이 지정되어 있지 않음"

#define LOG_CAMSGD_FAIL_TO_CALC_NEXTUPDATE_N              	 12005
#define LOG_CAMSGD_FAIL_TO_CALC_NEXTUPDATE_C                 "CRL 갱신 시각 계산 실패"

#define LOG_CAMSGD_FAIL_TO_GET_CRL_SETTINGS_N             	 12006
#define LOG_CAMSGD_FAIL_TO_GET_CRL_SETTINGS_C                "CRL 생성 실패(CRL 설정값 가져오기 실패)"

#define LOG_CAMSGD_FAIL_TO_GET_BASECRL_INFO_N             	 12007
#define LOG_CAMSGD_FAIL_TO_GET_BASECRL_INFO_C                "CRL 생성 실패(Complete CRL 정보가 없음)"

#define LOG_CAMSGD_FAIL_TO_SIGN_CRL_N                     	 12008
#define LOG_CAMSGD_FAIL_TO_SIGN_CRL_C                        "CRL 서명값 생성 실패"

#define LOG_CAMSGD_FAIL_TO_UPDATE_DB_CRL_N                	 12009
#define LOG_CAMSGD_FAIL_TO_UPDATE_DB_CRL_C                   "CRL 생성 실패(DB 값 갱신 실패)"

#define LOG_CAMSGD_INVALID_CRL_EXTENSION_N                	 12010
#define LOG_CAMSGD_INVALID_CRL_EXTENSION_C                   "잘못된 CRL 확장 영역 Template"

#define LOG_CAMSGD_INVALID_CRLENTRY_EXTENSION_N           	 12011
#define LOG_CAMSGD_INVALID_CRLENTRY_EXTENSION_C              "잘못된 CRL Entry 확장 영역 Template"

#define LOG_CAMSGD_FAIL_TO_ADD_CRLEXTENSION_N             	 12012
#define LOG_CAMSGD_FAIL_TO_ADD_CRLEXTENSION_C                "CRL 생성 실패(CRL 확장 영역 추가 실패)"

#define LOG_CAMSGD_FAIL_TO_ADD_CRLENTRY_N                 	 12013
#define LOG_CAMSGD_FAIL_TO_ADD_CRLENTRY_C                    "CRL 생성 실패(CRL Entry 추가 실패)"

#define LOG_CAMSGD_FAIL_TO_MAKE_CRL_N                     	 12014
#define LOG_CAMSGD_FAIL_TO_MAKE_CRL_C                        "CRL 생성 실패"

#define LOG_CAMSGD_FAIL_TO_SAVE_CRL_N                     	 12015
#define LOG_CAMSGD_FAIL_TO_SAVE_CRL_C                        "CRL 저장 실패"

/**
 * CTL 관련 이벤트
 */
#define LOG_CATEGORY_CTL                                     "CTL"
#define LOG_CAMSGD_CTL_UPDATED_N                          	 12501
#define LOG_CAMSGD_CTL_UPDATED_C                             "CTL 갱신"

#define LOG_CAMSGD_FAIL_TO_GET_DBSETTINGS_CTL_N           	 12502
#define LOG_CAMSGD_FAIL_TO_GET_DBSETTINGS_CTL_C              "CTL 갱신 실패(DB 설정값 가져오기 실패)"

#define LOG_CAMSGD_FAIL_TO_CONNECT_DB_CTL_N               	 12503
#define LOG_CAMSGD_FAIL_TO_CONNECT_DB_CTL_C                  "CTL 갱신 실패(DB 연결 실패)"

#define LOG_CAMSGD_INVALID_CTL_UPDATEPERIOD_N             	 12504
#define LOG_CAMSGD_INVALID_CTL_UPDATEPERIOD_C                "잘못된 CTL 갱신 주기"

#define LOG_CAMSGD_FAIL_TO_CALC_CTL_NEXTUPDATE_N          	 12505
#define LOG_CAMSGD_FAIL_TO_CALC_CTL_NEXTUPDATE_C             "CTL 갱신 시각 계산 실패"

#define LOG_CAMSGD_FAIL_TO_GET_CTL_SETTINGS_N             	 12506
#define LOG_CAMSGD_FAIL_TO_GET_CTL_SETTINGS_C                "CTL 생성 실패(CTL 설정값 가져오기 실패)"

#define LOG_CAMSGD_FAIL_TO_GET_CROSS_CERT_INFO_N          	 12507
#define LOG_CAMSGD_FAIL_TO_GET_CROSS_CERT_INFO_C             "잘못된 DB 데이터"

#define LOG_CAMSGD_FAIL_TO_GET_CROSS_CERT_N               	 12508
#define LOG_CAMSGD_FAIL_TO_GET_CROSS_CERT_C                  "잘못된 인증서 값"

#define LOG_CAMSGD_FAIL_TO_SIGN_CTL_N                     	 12509
#define LOG_CAMSGD_FAIL_TO_SIGN_CTL_C                        "CTL 서명값 생성 실패"

#define LOG_CAMSGD_INVALID_CTL_EXTENSION_N                	 12510
#define LOG_CAMSGD_INVALID_CTL_EXTENSION_C                   "잘못된 CTL 확장 영역 Template"

#define LOG_CAMSGD_FAIL_TO_UPDATE_DB_CTL_N                	 12511
#define LOG_CAMSGD_FAIL_TO_UPDATE_DB_CTL_C                   "CTL 생성 실패(DB 값 갱신 실패)"

#define LOG_CAMSGD_FAIL_TO_MAKE_CTL_N                     	 12512
#define LOG_CAMSGD_FAIL_TO_MAKE_CTL_C                        "CTL 생성 실패"

#define LOG_CAMSGD_FAIL_TO_SAVE_CTL_N                     	 12513
#define LOG_CAMSGD_FAIL_TO_SAVE_CTL_C                        "CTL 저장 실패"

/**
 * 예약 폐지 관련 이벤트
 */
#define LOG_CATEGORY_RESRV                                   "RESRV"
#define LOG_CAMSGD_RESERVED_CERTIFICATE_REVOKED_N         	 12601
#define LOG_CAMSGD_RESERVED_CERTIFICATE_REVOKED_C            "예약 폐지 과정 완료"

#define LOG_CAMSGD_FAIL_TO_GET_DBSETTINGS_RRCERT_N        	 12602
#define LOG_CAMSGD_FAIL_TO_GET_DBSETTINGS_RRCERT_C           "예약 폐지 실패(DB 설정값 가져오기 실패)"

#define LOG_CAMSGD_FAIL_TO_CONNECT_DB_RRCERT_N            	 12603
#define LOG_CAMSGD_FAIL_TO_CONNECT_DB_RRCERT_C               "예약 폐지 실패(DB연결 실패)"

#define LOG_CAMSGD_FAIL_TO_REVOKE_RESERVED_CERT_IN_DB_N   	 12604
#define LOG_CAMSGD_FAIL_TO_REVOKE_RESERVED_CERT_IN_DB_C      "폐지 예약된 인증서 폐지 실패(DB내 인증서 상태 갱신 실패)"

#define LOG_CAMSGD_FAIL_TO_CREATE_REQMESSAGE_FOR_RESERVED_CERT_N	 12605
#define LOG_CAMSGD_FAIL_TO_CREATE_REQMESSAGE_FOR_RESERVED_CERT_C   "예약 폐지를 하기 위한 요청 메시지 생성 실패"

#define LOG_CAMSGD_FAIL_TO_CONNECT_CA_FOR_RESERVED_CERT_N 	 12606
#define LOG_CAMSGD_FAIL_TO_CONNECT_CA_FOR_RESERVED_CERT_C    "예약 폐지를 요청하는 과정에서 CA 접속 실패"

#define LOG_CAMSGD_FAIL_TO_SEND_REQUEST_FOR_RESERVED_CERT_N	 12607
#define LOG_CAMSGD_FAIL_TO_SEND_REQUEST_FOR_RESERVED_CERT_C   "예약 폐지를 요청하는 과정에서 CA로 요청 메시지 전송 실패"

#define LOG_CAMSGD_FAIL_TO_RECV_RESPONSE_FOR_RESERVED_CERT_N	 12608
#define LOG_CAMSGD_FAIL_TO_RECV_RESPONSE_FOR_RESERVED_CERT_C   "예약 폐지를 요청하는 과정에서 CA로부터 응답 메시지 수신 실패"

#define LOG_CAMSGD_INVALID_MESSAGE_FROM_CA_FOR_RESERVED_CERT_N	 12609
#define LOG_CAMSGD_INVALID_MESSAGE_FROM_CA_FOR_RESERVED_CERT_C   "예약 폐지를 요청하는 과정에서 CA의 응답 메시지 해석 실패"

#define LOG_CAMSGD_ERROR_MESSAGE_FROM_CA_FOR_RESERVED_CERT_N	 12610
#define LOG_CAMSGD_ERROR_MESSAGE_FROM_CA_FOR_RESERVED_CERT_C   "예약 폐지를 요청하는 과정에서 CA로부터 에러 메시지 수신"

#define LOG_CAMSGD_REVOKE_REJECT_BY_CA_FOR_RESERVED_CERT_N	 12611
#define LOG_CAMSGD_REVOKE_REJECT_BY_CA_FOR_RESERVED_CERT_C   "폐지가 예약된 인증서에 대해 CA에서 폐지가 거부되었음"

/**
 * CMP 처리 관련 이벤트
 */
#define LOG_CATEGORY_CMP                                     "CMP"
#define LOG_CAMSGD_FAIL_TO_DECODE_REQUEST_MSG_N           	 13001
#define LOG_CAMSGD_FAIL_TO_DECODE_REQUEST_MSG_C              "메시지 DER Decoding 실패"

#define LOG_CAMSGD_FAIL_TO_REGISTER_CMP_MESSAGE_RECEIVE_HANDLER_N	 13002
#define LOG_CAMSGD_FAIL_TO_REGISTER_CMP_MESSAGE_RECEIVE_HANDLER_C   "메시지 수신 event에 대한 handler 등록 실패"

#define LOG_CAMSGD_FAIL_TO_REGISTER_TIMEOUT_HANDLER_N     	 13003
#define LOG_CAMSGD_FAIL_TO_REGISTER_TIMEOUT_HANDLER_C        "timeout에 대한 handler 등록 실패"

#define LOG_CAMSGD_TIMEOUT_CMP_CONNECTION_N               	 13004
#define LOG_CAMSGD_TIMEOUT_CMP_CONNECTION_C                  "timeout이 되어 클라이언트와 접속 종료"

#define LOG_CAMSGD_FAIL_TO_CONNECT_DB_CMP_N               	 13051
#define LOG_CAMSGD_FAIL_TO_CONNECT_DB_CMP_C                  "DB 접속 실패로 요청 처리 실패 "

#define LOG_CAMSGD_INVALID_SENDER_TYPE_N                  	 13052
#define LOG_CAMSGD_INVALID_SENDER_TYPE_C                     "sender가 directoryName이 아님 "

#define LOG_CAMSGD_FAIL_TO_RESOLVE_SENDER_N               	 13053
#define LOG_CAMSGD_FAIL_TO_RESOLVE_SENDER_C                  "sender값 해석 실패 "

#define LOG_CAMSGD_FAIL_TO_FIND_SENDER_INFO_N             	 13054
#define LOG_CAMSGD_FAIL_TO_FIND_SENDER_INFO_C                "sender값을 이용하여 요청자 정보를 찾는데 실패 "

#define LOG_CAMSGD_SENDER_NOT_TRUSTED_N                   	 13055
#define LOG_CAMSGD_SENDER_NOT_TRUSTED_C                      "sender 인증서 검증 실패 "

#define LOG_CAMSGD_WRONG_INTEGRITY_REFNUM_N               	 13056
#define LOG_CAMSGD_WRONG_INTEGRITY_REFNUM_C                  "잘못된 protection 방식(Reference number 사용) "

#define LOG_CAMSGD_MISSING_SENDERKID_N                    	 13057
#define LOG_CAMSGD_MISSING_SENDERKID_C                       "senderKID 값이 존재하지 않음"

#define LOG_CAMSGD_FAIL_TO_FIND_REFNUM_N                  	 13058
#define LOG_CAMSGD_FAIL_TO_FIND_REFNUM_C                     "주어진 reference number에 해당하는 정보를 찾는데 실패"

#define LOG_CAMSGD_FAIL_TO_FIND_SENDER_BY_SID_N           	 13059
#define LOG_CAMSGD_FAIL_TO_FIND_SENDER_BY_SID_C              "PKIEntityAuth(PKIAuthorityAuth) 테이블의 SID로 해당 요청자 정보를 찾는데 실패"

#define LOG_CAMSGD_REFNUM_NOT_AVAILABLE_N                 	 13060
#define LOG_CAMSGD_REFNUM_NOT_AVAILABLE_C                    "Reference number가 유효하지 않음"

#define LOG_CAMSGD_INVALID_SENDER_DN_IN_DB_N              	 13061
#define LOG_CAMSGD_INVALID_SENDER_DN_IN_DB_C                 "DB로부터 가져온 요청자의 DN값이 유효하지 않음"

#define LOG_CAMSGD_WRONG_INTEGRITY_REVPASS_N              	 13062
#define LOG_CAMSGD_WRONG_INTEGRITY_REVPASS_C                 "잘못된 protection 방식(RevPassPhrase 사용) "

#define LOG_CAMSGD_UNKNOWN_PROTECTIONALG_N                	 13063
#define LOG_CAMSGD_UNKNOWN_PROTECTIONALG_C                   "알 수 없는 방식의 protection 방식"

#define LOG_CAMSGD_REVPASS_NOT_REGISTERED_N               	 13064
#define LOG_CAMSGD_REVPASS_NOT_REGISTERED_C                  "RevPassPhrase가 등록되어 있지 않음"

#define LOG_CAMSGD_UNSUPPORTED_PKIMESSAGE_VERSION_N       	 13201
#define LOG_CAMSGD_UNSUPPORTED_PKIMESSAGE_VERSION_C          "잘못된 메시지 version"

#define LOG_CAMSGD_INVALID_RECIPIENT_TYPE_N               	 13202
#define LOG_CAMSGD_INVALID_RECIPIENT_TYPE_C                  "recipient가 directoryName이 아님"

#define LOG_CAMSGD_MISSING_RECIPIENT_N                    	 13203
#define LOG_CAMSGD_MISSING_RECIPIENT_C                       "recipient 값이 NULL임"

#define LOG_CAMSGD_WRONG_AUTHORITY_N                      	 13204
#define LOG_CAMSGD_WRONG_AUTHORITY_C                         "recipient 값이 인증기관의 Name과 일치하지 않음"

#define LOG_CAMSGD_WRONG_AUTHORITY_KID_N                  	 13205
#define LOG_CAMSGD_WRONG_AUTHORITY_KID_C                     "recipKID 값이 인증기관 공개키의 KID와 일치하지 않음"

#define LOG_CAMSGD_WRONG_MESSAGE_TIME_N                   	 13206
#define LOG_CAMSGD_WRONG_MESSAGE_TIME_C                      "PKIMessage의 시간 값이 제한된 범위를 벗어남"

#define LOG_CAMSGD_BAD_MESSAGE_CHECK_N                    	 13207
#define LOG_CAMSGD_BAD_MESSAGE_CHECK_C                       "protection 검증 실패"

#define LOG_CAMSGD_UNSUPPORTED_REQUEST_N                  	 13401
#define LOG_CAMSGD_UNSUPPORTED_REQUEST_C                     "지원하지 않는 요청"

#define LOG_CAMSGD_FAIL_TO_MAKE_RESPONSE_HEADER_N         	 13402
#define LOG_CAMSGD_FAIL_TO_MAKE_RESPONSE_HEADER_C            "응답 메시지의 Header 생성 실패"

#define LOG_CAMSGD_FAIL_TO_MAKE_RESPONSE_MESSAGE_N        	 13403
#define LOG_CAMSGD_FAIL_TO_MAKE_RESPONSE_MESSAGE_C           "응답 메시지 생성 실패"

#define LOG_CAMSGD_FAIL_TO_GET_SUBJECT_INFO_N             	 13451
#define LOG_CAMSGD_FAIL_TO_GET_SUBJECT_INFO_C                "발급을 위한 사용자 정보 가져오기 실패"

#define LOG_CAMSGD_INVALID_SUBJECT_DN_IN_DB_N             	 13452
#define LOG_CAMSGD_INVALID_SUBJECT_DN_IN_DB_C                "DB로부터 가져온 발급 대상의 DN값이 유효하지 않음"

#define LOG_CAMSGD_MISSING_SUBJECT_IN_CERTTEMPLATE_N      	 13453
#define LOG_CAMSGD_MISSING_SUBJECT_IN_CERTTEMPLATE_C         "인증서 발급 요청 메시지 안의 certTemplate의 subject 값이 존재하지 않음"

#define LOG_CAMSGD_MULTIPLE_SUBJECT_N                     	 13454
#define LOG_CAMSGD_MULTIPLE_SUBJECT_C                        "인증서 발급 요청 메시지 안의 certTemplate의 subject 값들이 서로 동일하지 않음"

#define LOG_CAMSGD_REQUESTED_BY_OTHERCA_N                 	 13455
#define LOG_CAMSGD_REQUESTED_BY_OTHERCA_C                    "타 CA는 다른 사용자의 인증서 발급을 요청할 수 없음"

#define LOG_CAMSGD_FAIL_TO_FIND_SUBJECT_INFO_N            	 13456
#define LOG_CAMSGD_FAIL_TO_FIND_SUBJECT_INFO_C               "발급 대상에 대한 정보를 찾는데 실패"

#define LOG_CAMSGD_DUPLICATE_DN_N                         	 13457
#define LOG_CAMSGD_DUPLICATE_DN_C                            "동일한 DN 값을 갖는 기존 사용자가 존재"

#define LOG_CAMSGD_REQUESTED_BY_USER_N                    	 13458
#define LOG_CAMSGD_REQUESTED_BY_USER_C                       "사용자는 다른 사용자의 인증서 발급을 요청할 수 없음"

#define LOG_CAMSGD_SENDER_NOT_AUTHORIZED_N                	 13459
#define LOG_CAMSGD_SENDER_NOT_AUTHORIZED_C                   "신청자에게 다른 사람에 대한 발급을 요청할 권한이 없음"

#define LOG_CAMSGD_RA_NOT_AUTHORIZED_N                    	 13460
#define LOG_CAMSGD_RA_NOT_AUTHORIZED_C                       "RA가 해당 사용자에 대한 발급을 요청할 권한이 없음"

#define LOG_CAMSGD_SUBJECT_NOT_AUTHORIZED_N               	 13461
#define LOG_CAMSGD_SUBJECT_NOT_AUTHORIZED_C                  "인증서 발급이 허가되지 않은 상호 인증 기관(CTL 사용)"

#define LOG_CAMSGD_SUBJECT_VLIMIT_EXPIRED_N               	 13462
#define LOG_CAMSGD_SUBJECT_VLIMIT_EXPIRED_C                  "발급 대상의 유효기간 만료"

#define LOG_CAMSGD_REQUESTED_USER_DELETED_N               	 13463
#define LOG_CAMSGD_REQUESTED_USER_DELETED_C                  "삭제된 사용자에 대한 발급 요청"

#define LOG_CAMSGD_REQUEST_FOR_THIS_CA_CERT_N             	 13464
#define LOG_CAMSGD_REQUEST_FOR_THIS_CA_CERT_C                "현 CA의 인증서 발급 요청"

#define LOG_CAMSGD_CCR_USED_FOR_NON_AUTHORITY_N           	 13465
#define LOG_CAMSGD_CCR_USED_FOR_NON_AUTHORITY_C              "ccr 메시지는 상호 인증시에만 사용됨"

#define LOG_CAMSGD_EMPTY_ISSUEREQUEST_BODY_N              	 13466
#define LOG_CAMSGD_EMPTY_ISSUEREQUEST_BODY_C                 "인증서 발급 요청 메시지의 Body가 비어있음"

#define LOG_CAMSGD_INVALID_CERTTEMPLATE_VERSION_N         	 13467
#define LOG_CAMSGD_INVALID_CERTTEMPLATE_VERSION_C            "인증서 요청 메시지의 certTemplate내의 version값이 잘못되었음"

#define LOG_CAMSGD_INVALID_CERTTEMPATE_ISSUER_N           	 13468
#define LOG_CAMSGD_INVALID_CERTTEMPATE_ISSUER_C              "인증서 요청 메시지의 certTemplate내의 issuer값이 잘못되었음"

#define LOG_CAMSGD_INVALID_CERTTEMPLATE_SIGNALG_N         	 13469
#define LOG_CAMSGD_INVALID_CERTTEMPLATE_SIGNALG_C            "인증서 요청 메시지의 certTemplate내의 signingAlg값이 잘못되었음"

#define LOG_CAMSGD_RESERVED0_N                            	 13470
#define LOG_CAMSGD_RESERVED0_C                               "인증서 요청 메시지의 certTemplate내의 subject값이 잘못되었음"

#define LOG_CAMSGD_FAIL_TO_VERIFY_POP_N                   	 13471
#define LOG_CAMSGD_FAIL_TO_VERIFY_POP_C                      "비공개키의 POP(Proof of possesion) 검증 실패"

#define LOG_CAMSGD_FAIL_TO_RESOLVE_PKIARCHIVEOPTS_N       	 13472
#define LOG_CAMSGD_FAIL_TO_RESOLVE_PKIARCHIVEOPTS_C          "pkiArchiveOptions 해석 실패"

#define LOG_CAMSGD_UNSUPPORTED_PKIARCHIVEOPTS_N           	 13473
#define LOG_CAMSGD_UNSUPPORTED_PKIARCHIVEOPTS_C              "지원되지 않는 방식의 pkiArhiveOptions"

#define LOG_CAMSGD_FAIL_TO_DECRYPT_PRIKEY_IN_ARCHIVEOPT_N 	 13474
#define LOG_CAMSGD_FAIL_TO_DECRYPT_PRIKEY_IN_ARCHIVEOPT_C    "PKIArchiveOptions 내의 비공개키 복호화 실패"

#define LOG_CAMSGD_FAIL_TO_RESOLVE_CERTREQMSG_N           	 13475
#define LOG_CAMSGD_FAIL_TO_RESOLVE_CERTREQMSG_C              "잘못된 certReqMsg 값"

#define LOG_CAMSGD_POP_RAVERIFIED_NOT_ALLOWED_N           	 13476
#define LOG_CAMSGD_POP_RAVERIFIED_NOT_ALLOWED_C              "허가되지 않은 POP 방식(RAVerified)"

#define LOG_CAMSGD_INCORRECT_NUM_OF_CERTREQ_N             	 13477
#define LOG_CAMSGD_INCORRECT_NUM_OF_CERTREQ_C                "발급을 요청하는 인증서의 개수가 사용자에게 설정되어 있는 개수와 일치하지 않음"

#define LOG_CAMSGD_BAD_KEYPOLICYID_N                      	 13478
#define LOG_CAMSGD_BAD_KEYPOLICYID_C                         "잘못된 Key policy ID 값"

#define LOG_CAMSGD_BAD_OLDCERTID_N                        	 13479
#define LOG_CAMSGD_BAD_OLDCERTID_C                           "잘못된 oldCertId 값"

#define LOG_CAMSGD_NO_CROSSCA_CERT_N                      	 13480
#define LOG_CAMSGD_NO_CROSSCA_CERT_C                         "인증서를 발급할 상호 인증기관의 인증서가 DB에 들어가 있지 않음"

#define LOG_CAMSGD_WRONG_PUBLICKEY_ALG_N                  	 13481
#define LOG_CAMSGD_WRONG_PUBLICKEY_ALG_C                     "공개키 알고리즘이 설정값과 일치하지 않음"

#define LOG_CAMSGD_WRONG_PUBLICKEY_LEN_N                  	 13482
#define LOG_CAMSGD_WRONG_PUBLICKEY_LEN_C                     "공개키 길이가 설정값과 일치하지 않음"

#define LOG_CAMSGD_INVALID_DOMAINPARAM_IN_DB_N            	 13483
#define LOG_CAMSGD_INVALID_DOMAINPARAM_IN_DB_C               "DB내의 도메인 파라메터 값이 올바르지 않음"

#define LOG_CAMSGD_WRONG_DOMAINPARAM_N                    	 13484
#define LOG_CAMSGD_WRONG_DOMAINPARAM_C                       "공개키 알고리즘 내의 도메인 파라메터 값이 설정값과 일치하지 않음"

#define LOG_CAMSGD_MISSING_PRIVATEKEY_N                   	 13485
#define LOG_CAMSGD_MISSING_PRIVATEKEY_C                      "비공개키를 저장하도록 되어 있으나 비공개키가 전달되어 오지 않았음"

#define LOG_CAMSGD_FAIL_TO_CHECK_POLICY_N                 	 13486
#define LOG_CAMSGD_FAIL_TO_CHECK_POLICY_C                    "인증서 요청 메시지가 사용자 정책과 일치하지 않음"

#define LOG_CAMSGD_FAIL_TO_GEN_CERT_N                     	 13487
#define LOG_CAMSGD_FAIL_TO_GEN_CERT_C                        "인증서 생성 실패"

#define LOG_CAMSGD_FAIL_TO_INSERT_CERT_TO_DB_N            	 13488
#define LOG_CAMSGD_FAIL_TO_INSERT_CERT_TO_DB_C               "생성된 인증서를 DB에 저장하는데 실패"

#define LOG_CAMSGD_FAIL_TO_ENCRYPT_PRIVATEKEY_N           	 13489
#define LOG_CAMSGD_FAIL_TO_ENCRYPT_PRIVATEKEY_C              "사용자 비공개키 암호화 실패"

#define LOG_CAMSGD_FAIL_TO_PREPARE_TO_INSERT_CERT_TO_DB_N 	 13490
#define LOG_CAMSGD_FAIL_TO_PREPARE_TO_INSERT_CERT_TO_DB_C    "생성된 인증서를 DB에 저장하는 과정에서 실패"

#define LOG_CAMSGD_FAIL_TO_ENCRYPT_CERT_N                 	 13491
#define LOG_CAMSGD_FAIL_TO_ENCRYPT_CERT_C                    "생성된 인증서를 암호화 하는데 실패"

#define LOG_CAMSGD_FAIL_TO_ENCODE_CERT_N                  	 13492
#define LOG_CAMSGD_FAIL_TO_ENCODE_CERT_C                     "인증서를 DER Encoding 하는데 실패"

#define LOG_CAMSGD_CERTIFICATE_REVOKED_N                  	 13501
#define LOG_CAMSGD_CERTIFICATE_REVOKED_C                     "인증서 폐지 과정 완료"

#define LOG_CAMSGD_EMPTY_REVREQUEST_BODY_N                	 13502
#define LOG_CAMSGD_EMPTY_REVREQUEST_BODY_C                   "인증서 폐지 요청 메시지의 Body가 비어있음"

#define LOG_CAMSGD_MISSING_SERIALNUMBER_TO_REVOKE_N       	 13503
#define LOG_CAMSGD_MISSING_SERIALNUMBER_TO_REVOKE_C          "폐지 요청 메시지에 폐지할 인증서의 일련 번호가 포함되어 있지 않음"

#define LOG_CAMSGD_FAIL_TO_FIND_CERT_TO_REVOKE_N          	 13504
#define LOG_CAMSGD_FAIL_TO_FIND_CERT_TO_REVOKE_C             "폐지할 인증서를 찾을 수 없음"

#define LOG_CAMSGD_CERT_ALREADY_REVOKED_N                 	 13505
#define LOG_CAMSGD_CERT_ALREADY_REVOKED_C                    "이미 폐지가 된 인증서에 대한 폐지 요청"

#define LOG_CAMSGD_SENDER_NOT_AUTHORIZED_REVOKE_CA_N      	 13506
#define LOG_CAMSGD_SENDER_NOT_AUTHORIZED_REVOKE_CA_C         "신청자는 인증기관 인증서에 대해서 폐지를 요청할 권한이 없음"

#define LOG_CAMSGD_REV_CA_REQUESTED_BY_RA_N_USER_N        	 13507
#define LOG_CAMSGD_REV_CA_REQUESTED_BY_RA_N_USER_C           "관리자나 해당 인증기관 이외에는 인증기관 인증서 폐지를 요청할 수 없음"

#define LOG_CAMSGD_REVOCATION_REQUESTED_BY_OTHERCA_N      	 13508
#define LOG_CAMSGD_REVOCATION_REQUESTED_BY_OTHERCA_C         "인증기관은 해당 인증기관의 인증서에 대해서만 폐지 요청을 할 수 있음"

#define LOG_CAMSGD_SENDER_NOT_AUTHORIZED_REVOKE_N         	 13509
#define LOG_CAMSGD_SENDER_NOT_AUTHORIZED_REVOKE_C            "신청자에게 다른 사람의 인증서에 대해 폐지를 요청할 권한이 없음"

#define LOG_CAMSGD_RA_NOT_AUTHORIZED_REVOKE_N             	 13510
#define LOG_CAMSGD_RA_NOT_AUTHORIZED_REVOKE_C                "등록기관은 자신에게 속한 사용자들의 인증서에 대해서만 폐지를 요청할 수 있음"

#define LOG_CAMSGD_REVOKE_REQUESTED_BY_USER_N             	 13511
#define LOG_CAMSGD_REVOKE_REQUESTED_BY_USER_C                "사용자는 다른 사용자의 인증서 폐지를 요청할 수 없음"

#define LOG_CAMSGD_REV_REQUESTED_BY_OTHERCA_N             	 13512
#define LOG_CAMSGD_REV_REQUESTED_BY_OTHERCA_C                "인증기관은 사용자의 인증서에 대해 폐지 요청을 할 수 없음"

#define LOG_CAMSGD_REVOKE_REQUEST_FOR_THIS_CA_CERT_N      	 13513
#define LOG_CAMSGD_REVOKE_REQUEST_FOR_THIS_CA_CERT_C         "현 CA의 인증서 폐지 요청"

#define LOG_CAMSGD_FAIL_TO_FIND_REVOKED_SUBJECT_BY_SID_N  	 13514
#define LOG_CAMSGD_FAIL_TO_FIND_REVOKED_SUBJECT_BY_SID_C     "해당 인증서의 주체에 대한 정보를 DB에서 찾는데 실패"

#define LOG_CAMSGD_FAIL_TO_REVOKE_CERT_IN_DB_N            	 13515
#define LOG_CAMSGD_FAIL_TO_REVOKE_CERT_IN_DB_C               "인증서 폐지 실패(DB내 인증서 상태 갱신 실패)"

#define LOG_CAMSGD_FAIL_TO_UPDATE_REVOKED_SUBJECT_INFO_N  	 13516
#define LOG_CAMSGD_FAIL_TO_UPDATE_REVOKED_SUBJECT_INFO_C     "인증서 폐지 실패(DB내 사용자 정보 갱신 실패)"

#define LOG_CAMSGD_CERT_REVOCATION_REJECT_BY_CA_N         	 13517
#define LOG_CAMSGD_CERT_REVOCATION_REJECT_BY_CA_C            "CA에서 인증서 폐지가 거부됨"

#define LOG_CAMSGD_UNSUPPORTED_INFOTYPEANDVALUE_N         	 13581
#define LOG_CAMSGD_UNSUPPORTED_INFOTYPEANDVALUE_C            "지원되지 않는 InfoTypeAndValue"

#define LOG_CAMSGD_FAIL_TO_DECODE_KEYPOLICYREQUEST_N      	 13582
#define LOG_CAMSGD_FAIL_TO_DECODE_KEYPOLICYREQUEST_C         "잘못된 형식의 KeyPolicyRequest"

#define LOG_CAMSGD_FAIL_TO_FIND_KEYPOLICY_SUBJECT_N       	 13583
#define LOG_CAMSGD_FAIL_TO_FIND_KEYPOLICY_SUBJECT_C          "KeyPolicy 요청 대상을 찾을 수 없음"

#define LOG_CAMSGD_NO_KEYPOLICY_ASSIGNED_TO_SUBJECT_N     	 13584
#define LOG_CAMSGD_NO_KEYPOLICY_ASSIGNED_TO_SUBJECT_C        "해당 요청 대상에게 할당된 KeyPolicy가 없음"

#define LOG_CAMSGD_KEYPOLICY_REQUEST_DISPATCHED_N         	 13585
#define LOG_CAMSGD_KEYPOLICY_REQUEST_DISPATCHED_C            "KeyPolicy 요청 메시지 처리 완료"

#define LOG_CAMSGD_FAIL_TO_SEND_RESPONSE_N                	 13551
#define LOG_CAMSGD_FAIL_TO_SEND_RESPONSE_C                   "응답 메시지 전송 실패"

#define LOG_CAMSGD_FAIL_TO_RECV_CONF_N                    	 13601
#define LOG_CAMSGD_FAIL_TO_RECV_CONF_C                       "Conf 메시지 수신 실패"

#define LOG_CAMSGD_MISSING_RECIPNONCE_N                   	 13651
#define LOG_CAMSGD_MISSING_RECIPNONCE_C                      "recipNonce 값이 존재하지 않음"

#define LOG_CAMSGD_WRONG_NONCE_N                          	 13652
#define LOG_CAMSGD_WRONG_NONCE_C                             "conf 메시지의 recipNonce 값이 응답 메시지의 senderNonce 값과 일치하지 않음"

#define LOG_CAMSGD_WRONG_TRANSACTION_ID_N                 	 13653
#define LOG_CAMSGD_WRONG_TRANSACTION_ID_C                    "transaction ID 값이 일치하지 않음"

#define LOG_CAMSGD_CERTIFICATE_ISSUED_N                   	 13701
#define LOG_CAMSGD_CERTIFICATE_ISSUED_C                      "인증서 신규 발급 과정 완료"

#define LOG_CAMSGD_ADDITIONAL_CERTIFICATE_ISSUED_N        	 13702
#define LOG_CAMSGD_ADDITIONAL_CERTIFICATE_ISSUED_C           "인증서 추가 발급 과정 완료"

#define LOG_CAMSGD_CROSS_CERTIFICATE_ISSUED_N             	 13703
#define LOG_CAMSGD_CROSS_CERTIFICATE_ISSUED_C                "상호 인증용 인증서 발급 과정 완료"

#define LOG_CAMSGD_CERTIFICATE_RENEWED_N                  	 13704
#define LOG_CAMSGD_CERTIFICATE_RENEWED_C                     "인증서 갱신 발급 과정 완료"

#define LOG_CAMSGD_INVALID_CONF_MESSAGE_N                 	 13705
#define LOG_CAMSGD_INVALID_CONF_MESSAGE_C                    "잘못된 Conf 메시지"

#define LOG_CAMSGD_ERROR_MESSAGE_RECEIVED_N               	 13706
#define LOG_CAMSGD_ERROR_MESSAGE_RECEIVED_C                  "Error 메시지 수신"

#define LOG_CAMSGD_FAIL_TO_REMOVE_REFNUM_N                	 13707
#define LOG_CAMSGD_FAIL_TO_REMOVE_REFNUM_C                   "Reference number 삭제 실패"

#define LOG_CAMSGD_FAIL_TO_UPDATE_ISSUED_SUBJECT_INFO_N   	 13708
#define LOG_CAMSGD_FAIL_TO_UPDATE_ISSUED_SUBJECT_INFO_C      "발급된 인증서 정보를 사용자 정보에 추가하는데 실패"

#define LOG_CAMSGD_FAIL_TO_INC_POLICY_NCERT_N             	 13709
#define LOG_CAMSGD_FAIL_TO_INC_POLICY_NCERT_C                "발급된 인증서의 해당 정책 Table의 발급된 인증서 개수 값을 증가시키는데 실패"

#define LOG_CAMSGD_FAIL_TO_UNHOLD_CERT_N                  	 13710
#define LOG_CAMSGD_FAIL_TO_UNHOLD_CERT_C                     "발급된 인증서의 상태를 변경하는데 실패"

#define LOG_CAMSGD_FAIL_TO_REVOKE_UNCONFIRMED_CERT_N      	 13801
#define LOG_CAMSGD_FAIL_TO_REVOKE_UNCONFIRMED_CERT_C         "인증서가 발급된 이후의 과정에서 에러가 발생하여, 발급된 인증서를 폐지하는데 실패"

#define LOG_CAMSGD_UNCONFIRMED_CERT_REVOKED_N             	 13802
#define LOG_CAMSGD_UNCONFIRMED_CERT_REVOKED_C                "인증서가 발급된 이후의 과정에서 에러가 발생하여, 발급된 인증서 폐지"

#define LOG_CAMSGD_FAIL_TO_RECV_MESSAGE_CMP_N                13803
#define LOG_CAMSGD_FAIL_TO_RECV_MESSAGE_CMP_C                "CMP 요청 메시지를 수신하는 데 실패"

#define LOG_CAMSGD_INVALID_PROTOCOL_CMP_N                    13804
#define LOG_CAMSGD_INVALID_PROTOCOL_CMP_C                    "알수 없는 방식의 TCP/IP 전송 방식"

#define LOG_CAMSGD_MESSAGE_TOO_LONG_CMP_N                    13805
#define LOG_CAMSGD_MESSAGE_TOO_LONG_CMP_C                    "PKI 메시지 길이 초과"

/**
 * RA 관련 이벤트
 */
#define LOG_CATEGORY_SYSTEM                                  "SYSTEM"
#define LOG_CAMSGD_FAIL_TO_MAKE_REQUEST_MESSAGE_N         	 20001
#define LOG_CAMSGD_FAIL_TO_MAKE_REQUEST_MESSAGE_C            "CA로의 요청 메시지 생성 실패"

#define LOG_CAMSGD_FAIL_TO_MAKE_POP_FOR_CA_N              	 20002
#define LOG_CAMSGD_FAIL_TO_MAKE_POP_FOR_CA_C                 "POP 생성 실패"

#define LOG_CAMSGD_FAIL_TO_CONNECT_CA_N                   	 20003
#define LOG_CAMSGD_FAIL_TO_CONNECT_CA_C                      "CA로의 접속 실패"

#define LOG_CAMSGD_FAIL_TO_SEND_REQUEST_TO_CA_N           	 20004
#define LOG_CAMSGD_FAIL_TO_SEND_REQUEST_TO_CA_C              "CA로의 요청 메시지 전송 실패"

#define LOG_CAMSGD_FAIL_TO_RECV_REPONSE_FROM_CA_N         	 20005
#define LOG_CAMSGD_FAIL_TO_RECV_REPONSE_FROM_CA_C            "CA로부터 응답 메시지 수신 실패"

#define LOG_CAMSGD_ERROR_MESSAGE_FROM_CA_N                	 20006
#define LOG_CAMSGD_ERROR_MESSAGE_FROM_CA_C                   "CA로부터 Error 메시지 수신"

#define LOG_CAMSGD_INVALID_MESSAGE_FROM_CA_N              	 20007
#define LOG_CAMSGD_INVALID_MESSAGE_FROM_CA_C                 "CA로부터 해석할 수 없는 메시지 수신"

#define LOG_CAMSGD_FAIL_TO_SEND_CONF_TO_CA_N              	 20008
#define LOG_CAMSGD_FAIL_TO_SEND_CONF_TO_CA_C                 "CA로 CONFIRM 메시지 전송 실패"

#define LOG_CAMSGD_CERT_ISSUE_REJECTED_BY_CA_N            	 20009
#define LOG_CAMSGD_CERT_ISSUE_REJECTED_BY_CA_C               "CA로부터 인증서 발급 받는데 실패 "

/**
 * 통계 로그
 */
#define LOG_CATEGORY_AUDIT                                   "AUDIT"
#define LOG_CAMSGD_CERT_ISSUED_N                          	 30001
#define LOG_CAMSGD_CERT_ISSUED_C                             "인증서 신규 발급"

#define LOG_CAMSGD_ADDITIONAL_CERT_ISSUED_N               	 30002
#define LOG_CAMSGD_ADDITIONAL_CERT_ISSUED_C                  "인증서 추가 발급"

#define LOG_CAMSGD_CROSS_CERT_ISSUED_N                    	 30003
#define LOG_CAMSGD_CROSS_CERT_ISSUED_C                       "상호 인증용 인증서 발급"

#define LOG_CAMSGD_CERT_RENEWED_N                         	 30004
#define LOG_CAMSGD_CERT_RENEWED_C                            "인증서 갱신"

#define LOG_CAMSGD_CERT_REVOKED_N                         	 30005
#define LOG_CAMSGD_CERT_REVOKED_C                            "인증서 폐지"

