/**
 * @file     ControlDaemonLogTableDefine.hpp
 *
 * @desc     CONTROL_DAEMON 로그 리스트
 * @author   조현래(hrcho@pentasecurity.com)
 * @since    2002.01.02
 *
 */

/**
 * NOTE : Do not modify the content of this file directly. If this file is regenerated by
 *        file-generating script your modification will be overwritten
 */

/**
 * Authority 공통 이벤트
 */
#ifndef ISSAC_CONTROL_DAEMON_LOG_TABLE_DEFINE
#define ISSAC_CONTROL_DAEMON_LOG_TABLE_DEFINE

#define LOG_CATEGORY_SYSTEM                                     "SYSTEM"

#define LOG_CONTROL_DAEMON_NO_SUCH_COMMAND_N                    51001
#define LOG_CONTROL_DAEMON_NO_SUCH_COMMAND_C                    "요청한 명령이 존재하지 않습니다."

#define LOG_CONTROL_DAEMON_RUNTIME_ERROR_N                      51002
#define LOG_CONTROL_DAEMON_RUNTIME_ERROR_C                      "실행 오류"

#define LOG_CONTROL_DAEMON_NO_SUCH_SENDER_ERROR_N               51003
#define LOG_CONTROL_DAEMON_NO_SUCH_SENDER_ERROR_C               "요청자 인증 오류"

#define LOG_CONTROL_DAEMON_PROCESS_COMMAND_N                    51004
#define LOG_CONTROL_DAEMON_PROCESS_COMMAND_C                    "요청 명령 수행"

#define LOG_CONTROL_TIMEOUT_TERMINATE_N                         51005
#define LOG_CONTROL_TIMEOUT_TERMINATE_C                         "타임아웃 종료"

#endif
