/**
 * @file     PKILogTableDefine.hpp
 *
 * @desc     AUTHORITY 로그 리스트
 * @author   조현래(hrcho@pentasecurity.com)
 * @since    2002.01.02
 *
 */

/** 
 * NOTE : Do not modify the content of this file directly. If this file is regenerated by
 *        file-generating script your modification will be overwritten
 */

/** 
 * Authority 공통 이벤트
 */
#define LOG_CATEGORY_SYSTEM                                  "SYSTEM"

#define LOG_AUTHORITY_INVALID_HISTORY_FILE_N                 	 41001
#define LOG_AUTHORITY_INVALID_HISTORY_FILE_C                    "신규 실행 실패(잘못된 History 파일)"

#define LOG_AUTHORITY_FAIL_TO_LOAD_PRIKEY_N                  	 41002
#define LOG_AUTHORITY_FAIL_TO_LOAD_PRIKEY_C                     "신규 실행 실패(비공개키 복호화 실패)"

#define LOG_AUTHORITY_FAIL_TO_LOAD_CERT_N                    	 41003
#define LOG_AUTHORITY_FAIL_TO_LOAD_CERT_C                       "신규 실행 실패(인증서 가져오기 실패)"

#define LOG_AUTHORITY_FAIL_TO_GET_SYMMALG_N                  	 41005
#define LOG_AUTHORITY_FAIL_TO_GET_SYMMALG_C                     "기본 대칭키 암호화 알고리즘 값 가져오기 실패"

#define LOG_AUTHORITY_FAIL_TO_GET_CA_INFO_N                  	 41006
#define LOG_AUTHORITY_FAIL_TO_GET_CA_INFO_C                     "신규 실행 실패(DB로부터 초기화를 위한 정보를 가져오는데 실패)"

#define LOG_AUTHORITY_FAIL_TO_GET_DBSETTINGS_START_N         	 41007
#define LOG_AUTHORITY_FAIL_TO_GET_DBSETTINGS_START_C            "신규 실행 실패(DB 설정값 가져오기 실패)"

#define LOG_AUTHORITY_FAIL_TO_CONNECT_DB_START_N             	 41008
#define LOG_AUTHORITY_FAIL_TO_CONNECT_DB_START_C                "신규 실행 실패(DB 연결 실패)"

#define LOG_AUTHORITY_INVALID_DB_TABLE_N                     	 41009
#define LOG_AUTHORITY_INVALID_DB_TABLE_C                        "신규 실행 실패(잘못된 DB Table)"

