MAKE_ROOT = ../../..
include $(MAKE_ROOT)/make/Makefile.var

MODULE_NAME = authority
MAKELIB = yes
DEST = ../build

INC_DIR = $(CIS_INC_PATH) $(PKILIB_INC_PATH) $(PKISYS21_INC_PATH) $(PKI31_DBLIB_INC_PATH)

include $(MAKE_ROOT)/make/Makefile.cmm
